In [4]:
from QuickInit import *
import numpy as np
import pandas as pd

In [5]:
#One Hot Encode
from sklearn.preprocessing import OneHotEncoder
Sample_data_Pandas=FillNaN_PD()
Sample_data_Numpy=FillNaN_NP()
enc_data=OneHotEncoder()
print(Sample_data_Numpy)
ans=enc_data.fit_transform(Sample_data_Numpy)
print(ans)
print(Sample_data_Pandas)

[[ 0.  0. 32. ...  2.  2.  2.]
 [ 0.  0. 29. ...  0.  0.  0.]
 [ 0.  0. 31. ...  6. 10. 10.]
 ...
 [ 0.  0. 28. ...  0.  0.  0.]
 [ 0.  0. 23. ...  1.  7.  1.]
 [ 1.  0. 35. ...  1.  1.  1.]]
  (0, 0)	1.0
  (0, 2)	1.0
  (0, 18)	1.0
  (0, 46)	1.0
  (0, 48)	1.0
  (0, 50)	1.0
  (0, 52)	1.0
  (0, 54)	1.0
  (0, 56)	1.0
  (0, 59)	1.0
  (0, 61)	1.0
  (0, 62)	1.0
  (0, 64)	1.0
  (0, 65)	1.0
  (0, 68)	1.0
  (0, 69)	1.0
  (0, 71)	1.0
  (0, 73)	1.0
  (0, 76)	1.0
  (0, 77)	1.0
  (0, 83)	1.0
  (0, 106)	1.0
  (0, 125)	1.0
  (0, 129)	1.0
  (0, 133)	1.0
  :	:
  (11016, 156163)	1.0
  (11016, 156179)	1.0
  (11016, 156192)	1.0
  (11016, 156204)	1.0
  (11016, 156217)	1.0
  (11016, 156523)	1.0
  (11016, 156592)	1.0
  (11016, 156887)	1.0
  (11016, 157067)	1.0
  (11016, 157353)	1.0
  (11016, 158166)	1.0
  (11016, 164665)	1.0
  (11016, 169837)	1.0
  (11016, 170596)	1.0
  (11016, 170611)	1.0
  (11016, 170625)	1.0
  (11016, 170658)	1.0
  (11016, 170689)	1.0
  (11016, 170713)	1.0
  (11016, 170735)	1.0
  (11016, 

In [32]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler=scaler.fit(Sample_data_Pandas)
result=scaler.transform(Sample_data_Pandas)
print(result)


[[0.         0.         0.54237288 ... 0.05714286 0.01104972 0.01515152]
 [0.         0.         0.49152542 ... 0.         0.         0.        ]
 [0.         0.         0.52542373 ... 0.17142857 0.05524862 0.07575758]
 ...
 [0.         0.         0.47457627 ... 0.         0.         0.        ]
 [0.         0.         0.38983051 ... 0.02857143 0.03867403 0.00757576]
 [1.         0.         0.59322034 ... 0.02857143 0.00552486 0.00757576]]


In [33]:
#StandarLize The Data
from sklearn.preprocessing import StandardScaler
result_=scaler.inverse_transform(result)
scaler_2=StandardScaler()
scaler_2.fit(Sample_data_Pandas)
print(scaler_2)
x_std=scaler_2.transform(result_)
print(result_)


StandardScaler(copy=True, with_mean=True, with_std=True)
[[ 0.  0. 32. ...  2.  2.  2.]
 [ 0.  0. 29. ...  0.  0.  0.]
 [ 0.  0. 31. ...  6. 10. 10.]
 ...
 [ 0.  0. 28. ...  0.  0.  0.]
 [ 0.  0. 23. ...  1.  7.  1.]
 [ 1.  0. 35. ...  1.  1.  1.]]
