In [22]:
import numpy as np
import pandas as pd
import os
# Fill The Data using SimpleImputer
from sklearn.impute import SimpleImputer
df= pd.read_csv('sample/model_sample.csv',header=0)
numpy_Data=np.array(df)
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
Sample_data=np.delete(numpy_Data,0,axis=1)
imp.fit(Sample_data)
print(Sample_data)

[[0 0.0 32.0 ... 2.0 2.0 2.0]
 [0 0.0 29.0 ... nan nan nan]
 [0 0.0 31.0 ... 6.0 10.0 10.0]
 ...
 [0 0.0 28.0 ... 0.0 0.0 0.0]
 [0 0.0 23.0 ... 1.0 7.0 1.0]
 [1 0.0 35.0 ... 1.0 1.0 1.0]]


In [24]:
#One Hot Encode
from sklearn.preprocessing import OneHotEncoder
Sample_data_Pandas=pd.DataFrame(Sample_data)
Sample_data_Pandas.fillna(0,inplace = True)
#print(Sample_data_Pandas)
Sample_data_Numpy=np.array(Sample_data_Pandas)
enc_data=OneHotEncoder()
enc_data.fit_transform(Sample_data_Numpy)
#print(enc_data)

       0    1     2    3    4    5    6    7    8    9    ...  190  191  192  \
0        0  0.0  32.0    0    0    0    0    0    0    1  ...  1.0  1.0  2.0   
1        0  0.0  29.0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0   
2        0  0.0  31.0    0    0    0    0    0    0    0  ...  2.0  2.0  4.0   
3        0  0.0  22.0    0    0    0    0    0    0    0  ...  3.0  3.0  3.0   
4        0  0.0  31.0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0   
...    ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
11012    0  0.0  29.0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0   
11013    1  0.0  25.0    0    0    0    0    0    0    0  ...  3.0  3.0  3.0   
11014    0  0.0  28.0    0    0    0    0    0    0    0  ...  0.0  0.0  0.0   
11015    0  0.0  23.0    0    0    0    0    0    0    0  ...  1.0  0.0  3.0   
11016    1  0.0  35.0    0    0    0    0    0    0    0  ...  1.0  1.0  1.0   

       193  194  195  196  197   198   