In [3]:
from QuickInit import *
import numpy as np
import pandas as pd

In [32]:
#One Hot Encode
from sklearn.preprocessing import OneHotEncoder
Sample_data_Pandas=FillNaN_PD('sample/model_sample_SMOTE.csv')
Sample_data_Numpy=FillNaN_NP('sample/model_sample_SMOTE.csv')
enc_data=OneHotEncoder()
ans=enc_data.fit_transform(Sample_data_Numpy)
print(Sample_data_Numpy)
dateframe=pd.DataFrame(Sample_data_Numpy)
dateframe.to_csv('sample/model_sample_OneHotEncode.csv')

sample/model_sample_SMOTE.csv
[[32.  0.  0. ...  2.  2.  0.]
 [29.  0.  0. ...  0.  0.  0.]
 [31.  0.  0. ... 10. 10.  0.]
 ...
 [28.  0.  0. ...  0.  0.  0.]
 [23.  0.  0. ...  7.  1.  0.]
 [35.  0.  0. ...  1.  1.  1.]]


In [ ]:
#数值
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler=scaler.fit(Sample_data_Pandas)
result=scaler.transform(Sample_data_Pandas)
print(result)


In [ ]:
#StandarLize The Data
from sklearn.preprocessing import StandardScaler
result_=scaler.inverse_transform(result)
scaler_2=StandardScaler()
scaler_2.fit(Sample_data_Pandas)
print(scaler_2)
x_std=scaler_2.transform(result_)
print(result_)

In [ ]:
#
from QuickInit import *
Sample_RandomSearch('sample\model_sample_SMOTE.csv')