In [22]:
import numpy as np
import pandas as pd
import os
# Fill The Data using SimpleImputer
from sklearn.impute import SimpleImputer
df= pd.read_csv('sample/model_sample.csv',header=0)
numpy_Data=np.array(df)
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
Sample_data=np.delete(numpy_Data,0,axis=1)
imp.fit(Sample_data)
print(Sample_data)

[[0 0.0 32.0 ... 2.0 2.0 2.0]
 [0 0.0 29.0 ... nan nan nan]
 [0 0.0 31.0 ... 6.0 10.0 10.0]
 ...
 [0 0.0 28.0 ... 0.0 0.0 0.0]
 [0 0.0 23.0 ... 1.0 7.0 1.0]
 [1 0.0 35.0 ... 1.0 1.0 1.0]]


In [29]:
#One Hot Encode
from sklearn.preprocessing import OneHotEncoder
Sample_data_Pandas=pd.DataFrame(Sample_data)
Sample_data_Pandas.fillna(0,inplace = True)
Sample_data_Numpy=np.array(Sample_data_Pandas)
enc_data=OneHotEncoder()
print(Sample_data_Numpy)
ans=enc_data.fit_transform(Sample_data_Numpy)
print(ans)

[[ 0.  0. 32. ...  2.  2.  2.]
 [ 0.  0. 29. ...  0.  0.  0.]
 [ 0.  0. 31. ...  6. 10. 10.]
 ...
 [ 0.  0. 28. ...  0.  0.  0.]
 [ 0.  0. 23. ...  1.  7.  1.]
 [ 1.  0. 35. ...  1.  1.  1.]]
  (0, 0)	1.0
  (0, 2)	1.0
  (0, 18)	1.0
  (0, 46)	1.0
  (0, 48)	1.0
  (0, 50)	1.0
  (0, 52)	1.0
  (0, 54)	1.0
  (0, 56)	1.0
  (0, 59)	1.0
  (0, 61)	1.0
  (0, 62)	1.0
  (0, 64)	1.0
  (0, 65)	1.0
  (0, 68)	1.0
  (0, 69)	1.0
  (0, 71)	1.0
  (0, 73)	1.0
  (0, 76)	1.0
  (0, 77)	1.0
  (0, 83)	1.0
  (0, 106)	1.0
  (0, 125)	1.0
  (0, 129)	1.0
  (0, 133)	1.0
  :	:
  (11016, 156163)	1.0
  (11016, 156179)	1.0
  (11016, 156192)	1.0
  (11016, 156204)	1.0
  (11016, 156217)	1.0
  (11016, 156523)	1.0
  (11016, 156592)	1.0
  (11016, 156887)	1.0
  (11016, 157067)	1.0
  (11016, 157353)	1.0
  (11016, 158166)	1.0
  (11016, 164665)	1.0
  (11016, 169837)	1.0
  (11016, 170596)	1.0
  (11016, 170611)	1.0
  (11016, 170625)	1.0
  (11016, 170658)	1.0
  (11016, 170689)	1.0
  (11016, 170713)	1.0
  (11016, 170735)	1.0
  (11016, 

[[1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0.]]
